name: Aliyun Image CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 安全文件传输步骤
      - name: Secure File Transfer
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT || 22 }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yaml"
          target: "/tmp/docker-compose.yaml"
          strip_components: 1

      - name: SSH Deployment
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT || 22 }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 创建应用目录（使用临时提权）
            sudo mkdir -p /opt/my-app

            # 原子化文件替换
            mv -f /tmp/docker-compose.yaml /opt/my-app/docker-compose.yaml
            cd /opt/my-app

            # 安全登录镜像仓库
            echo "${{ secrets.ALIYUN_PASSWORD }}" | docker login \
              --username "${{ secrets.ALIYUN_USERNAME }}" \
              --password-stdin "${{ secrets.ALIYUN_REGISTRY }}"

            # 部署命令
            docker-compose -f docker-compose.yaml pull
            docker-compose -f docker-compose.yaml up -d \
              --force-recreate \
              --remove-orphans \
              --no-build

            # 安全清理（保留最近3个版本）
            docker image prune -af --filter "label=maintainer=ci-system" --filter "until=72h"